import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner2.jpg",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Relaxed Fit Khakis",
      slug: "pant4",
      category: "Pants",
      image: "/images/pant4.jpg",
      price: 75,
      brand: "BrandA",
      rating: 4.0,
      numReviews: 10,
      countInStock: 15,
      description: "A popular pair of pants",
      isFeatured: false,
    },
    {
      name: "Stretch Dress Pants",
      slug: "pant5",
      category: "Pants",
      image: "/images/pant5.jpg",
      price: 80,
      brand: "BrandB",
      rating: 3.5,
      numReviews: 8,
      countInStock: 20,
      description: "A stylish pair of pants",
      isFeatured: true,
    },
    {
      name: "Casual Cargo Pants",
      slug: "pant6",
      category: "Pants",
      image: "/images/pant6.jpg",
      price: 85,
      brand: "BrandC",
      rating: 4.2,
      numReviews: 12,
      countInStock: 10,
      description: "A comfortable pair of pants",
      isFeatured: false,
    },
    {
      name: "Athletic Joggers",
      slug: "pants1",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 70,
      brand: "BrandD",
      rating: 3.8,
      numReviews: 5,
      countInStock: 25,
      description: "A durable pair of pants",
      isFeatured: true,
    },
    {
      name: "Slim Fit Jeans",
      slug: "pants2",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "BrandE",
      rating: 4.5,
      numReviews: 15,
      countInStock: 18,
      description: "A stylish pair of pants",
      isFeatured: false,
    },
    {
      name: "Classic Chinos",
      slug: "pants3",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 90,
      brand: "BrandF",
      rating: 3.0,
      numReviews: 7,
      countInStock: 22,
      description: "A comfortable pair of pants",
      isFeatured: false,
    },
    {
      name: "Oxford Button-Down",
      slug: "shirt6",
      category: "Shirts",
      image: "/images/shirt6.jpg",
      price: 85,
      brand: "BrandG",
      rating: 4.3,
      numReviews: 9,
      countInStock: 30,
      description: "A trendy shirt",
      isFeatured: true,
    },
    {
      name: "Polo Shirt",
      slug: "shirt1",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "BrandH",
      rating: 4.0,
      numReviews: 10,
      countInStock: 15,
      description: "A popular shirt",
      isFeatured: false,
    },
    {
      name: "Crew Neck Tee",
      slug: "shirt2",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "BrandI",
      rating: 3.5,
      numReviews: 8,
      countInStock: 20,
      description: "A stylish shirt",
      isFeatured: true,
    },
    {
      name: "Henley Shirt",
      slug: "shirt3",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "BrandJ",
      rating: 4.2,
      numReviews: 12,
      countInStock: 10,
      description: "A comfortable shirt",
      isFeatured: false,
    },
    {
      name: "Flannel Plaid Shirt",
      slug: "shirt4",
      category: "Shirts",
      image: "/images/shirt4.jpg",
      price: 75,
      brand: "BrandK",
      rating: 3.8,
      numReviews: 5,
      countInStock: 25,
      description: "A durable shirt",
      isFeatured: true,
    },
    {
      name: "Flannel Plaid Shirt",
      slug: "shirt5",
      category: "Shirts",
      image: "/images/shirt5.jpg",
      price: 95,
      brand: "BrandL",
      rating: 4.5,
      numReviews: 15,
      countInStock: 18,
      description: "A stylish shirt",
      isFeatured: false,
    },
  ],
};

export default data;
